language: rust
cache: cargo
rust:
    - stable
os:
    - linux
    - osx
    - windows
matrix:
    fast_finish: true
    allow_failures:
         - os: windows

before_script:
    - rustup component add rustfmt
    - rustup component add clippy
    - command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

script:
    - cargo fmt --all -- --check
    - cargo clippy --all
    - cargo check
    - cargo build
    - cargo test --release
    - cargo doc --no-deps
