environment:
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          BITS: 64
          MSYS2: 1
        - TARGET: i686-pc-windows-gnu
          BITS: 32
          MSYS2: 1

branches:
    only:
        - master

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%

    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo test --release -v --no-fail-fast

cache:
    - target
    - C:\Users\appveyor\.cargo\registry
